import Input from "@/components/Input";
import Head from "next/head";
import { useCallback, useState } from "react";

const Auth = () => {
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");

  const [variant, setVariant] = useState("login");

  const toggleVariant = useCallback(() => {
    setVariant((currentVariant) =>
      currentVariant === "login" ? "register" : "login"
    );
  }, []);

  return (
    <>
      <Head>
        <title>
          {variant === "login" ? "Đang đăng nhập..." : "Đang đăng ký..."}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-full w-full bg-[url('/images/bg-login.jpg')] bg-no-repeat bg-center bg-fixed bg-cover">
        <div className="bg-black w-full h-full lg:bg-opacity-50">
          <nav className="px-12 py-5">
            <img src="/images/logo.png" alt="Logo" className="h-16" />
          </nav>
          <div className="flex justify-center">
            <div className="bg-black bg-opacity-70 px-16 py-16 self-center mt-2 lg:max-w-md rounded-md w-full">
              <h2 className="text-white text-4xl mb-8 font-semibold">
                {variant === "login" ? "Đăng nhập" : "Đăng ký"}
              </h2>
              <div className="flex flex-col gap-4">
                {variant === "register" && (
                  <Input
                    label="Tên người dùng"
                    onChange={(ev: any) => setName(ev.target.value)}
                    id="name"
                    value={name}
                  />
                )}
                <Input
                  label="Địa chỉ Email"
                  onChange={(ev: any) => setEmail(ev.target.value)}
                  id="email"
                  type="email"
                  value={email}
                />
                <Input
                  label="Nhập mật khẩu"
                  onChange={(ev: any) => setPassword(ev.target.value)}
                  id="password"
                  type="password"
                  value={password}
                />
              </div>
              <button className="bg-orange-600 py-3 text-white rounded-md w-full mt-10 hover:bg-orange-700 transition">
                {variant === "login" ? "Đăng nhập" : "Đăng ký"}
              </button>
              <p className="text-neutral-500 mt-5 text-center">
                {variant === "login"
                  ? "Bạn chưa có tài khoản ?"
                  : "Bạn đã có tài khoản ?"}
                <span
                  onClick={toggleVariant}
                  className="text-white ml-1 hover:underline cursor-pointer"
                >
                  {variant === "login" ? "Tạo tài khoản" : "Đăng nhập "}
                </span>
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Auth;
